# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - "build/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-raport:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - run: echo "filename=$(./scripts/get_filename.sh)" >> "$GITHUB_ENV"
      - name: Generate raport
        env:
          ES_USER: ${{ secrets.OPENCB_ELASTIC_USER }}
          ES_PASSWORD: ${{ secrets.OPENCB_ELASTIC_PSWD }}
        run: |
          ./scripts/create_post_with_front_matter.sh "$HOME/${{ env.filename }}"
          echo "GitHub Action on $(date)" >> "$HOME/${{ env.filename }}"
      - name: Upload raport
        uses: actions/upload-artifact@v2
        with:
          name: raport
          path: $HOME/${{ env.filename }}
      - name: Push raport
        uses: ./actions/push-raport-to-gh-page/
#        run: |
#          if [ -s "$HOME/${{ env.filename }}" ]; then
#            echo "The raport file is non-empty."
#            git checkout jekyll-gh-page
#
#            mkdir -p "./_posts"
#            cat $HOME/${{ env.filename }} > "./_posts/${{ env.filename }}"
#
#            git config --global user.name "GitHub Actions"
#            git config --global user.email "mgajek@virtuslab.com"
#
#            git add "./_posts/${{ env.filename }}"
#            git commit -m "Upload build raport"
#            git push origin jekyll-gh-page
#          else
#            echo "The raport file is empty."
#            exit 0
#          fi
