# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - "build/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  create-raport:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - run: echo ::set-output name=filename::"$(./scripts/get_filename.sh)"
        id: filename
      - name: Generate raport
        env:
          ES_USER: ${{ secrets.OPENCB_ELASTIC_USER }}
          ES_PASSWORD: ${{ secrets.OPENCB_ELASTIC_PSWD }}
        run: echo "GitHub Action on $(date)">> "~/${{ steps.filename.outputs.filename }}"
      - name: Push raport
        run: |
          if [ -s "~/${{ steps.filename.outputs.filename }}" ]; then
            echo "The raport file is non-empty."
            git checkout jekyll-gh-page
          
            ./scripts/create_post_with_front_matter.sh "./_posts/${{ steps.filename.outputs.filename }}"
            cat ~/${{ steps.filename.outputs.filename }} >> "./_posts/${{ steps.filename.outputs.filename }}"
          
            git config --global user.name "GitHub Actions"
            git config --global user.email "mgajek@virtuslab.com"
          
            git commit -am "Upload build raport"
            git push origin jekyll-gh-page
          else
            echo "The raport file is empty."
            exit 0
          fi
